package tokens

import (
	"bytes"
	"text/template"
)

const installScriptTemplate = `#!/bin/bash
# ============================================================================
# NetMirror Auto-Registration Installer
# Generated for: {{.NodeName}}
# Token expires: {{.ExpiresAt}}
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration (embedded from master node)
MASTER_URL="{{.MasterURL}}"
TOKEN="{{.Token}}"
NODE_NAME="{{.NodeName}}"
NODE_LOCATION="{{.NodeLocation}}"

# User-configurable via environment variables
PORT="${PORT:-3000}"
IMAGE="${IMAGE:-soyorins/netmirror-agent:latest}"
DEPLOY_DIR="${DEPLOY_DIR:-./netmirror-node}"

# Helper functions
log() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Banner
echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          NetMirror Auto-Registration Installer               ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Node: $NODE_NAME"
echo "║  Location: $NODE_LOCATION"
echo "║  Master: $MASTER_URL"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Step 1: Check Docker
log "Checking Docker installation..."
if ! command -v docker &> /dev/null; then
    log "Docker not found. Installing Docker..."
    if curl -fsSL https://get.docker.com | sh; then
        success "Docker installed successfully"
        # Add current user to docker group
        if [ "$EUID" -ne 0 ]; then
            sudo usermod -aG docker $USER 2>/dev/null || true
        fi
    else
        error "Failed to install Docker. Please install Docker manually and try again."
    fi
else
    success "Docker is installed"
fi

# Ensure Docker daemon is running
if ! docker info &> /dev/null; then
    log "Starting Docker daemon..."
    if command -v systemctl &> /dev/null; then
        sudo systemctl start docker 2>/dev/null || true
        sleep 2
    fi
    if ! docker info &> /dev/null; then
        error "Docker daemon is not running. Please start Docker and try again."
    fi
fi

# Step 2: Create deployment directory
log "Setting up deployment directory: $DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"
cd "$DEPLOY_DIR"

# Step 3: Detect external IP
log "Detecting external IP address..."
EXTERNAL_IP=""
for service in "ifconfig.me" "ipinfo.io/ip" "api.ipify.org" "icanhazip.com"; do
    EXTERNAL_IP=$(curl -s -4 --connect-timeout 5 "$service" 2>/dev/null | tr -d '\n')
    if [[ -n "$EXTERNAL_IP" && "$EXTERNAL_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        break
    fi
done

if [ -z "$EXTERNAL_IP" ]; then
    warn "Could not detect external IP. Using localhost."
    EXTERNAL_IP="localhost"
fi

# Allow custom URL override via NODE_URL environment variable
NODE_URL="${NODE_URL:-http://$EXTERNAL_IP:$PORT}"
log "Node URL: $NODE_URL"

# Step 4: Create environment file
log "Creating configuration..."
cat > .env << EOF
# NetMirror Node Configuration
# Generated by master node installer

# Agent Mode - API only, no UI serving
AGENT_MODE=true

LISTEN_IP=0.0.0.0
HTTP_PORT=$PORT

# Node Identity
LG_CURRENT_NAME=$NODE_NAME
LG_CURRENT_LOCATION=$NODE_LOCATION
LG_CURRENT_URL=$NODE_URL
LOCATION=$NODE_LOCATION

# Features
DISPLAY_TRAFFIC=true
UTILITIES_PING=true
UTILITIES_MTR=true
UTILITIES_TRACEROUTE=true
UTILITIES_SPEEDTESTDOTNET=true
UTILITIES_FAKESHELL=true
UTILITIES_IPERF3=true
ENABLE_SPEEDTEST=true

# Storage
DATA_DIR=/data
EOF

success "Configuration created"

# Step 5: Create data directory
mkdir -p ./data

# Step 6: Stop existing container if running
CONTAINER_NAME="netmirror-node-$PORT"
log "Checking for existing container..."
if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
    log "Stopping existing container: $CONTAINER_NAME"
    docker stop "$CONTAINER_NAME" 2>/dev/null || true
    docker rm "$CONTAINER_NAME" 2>/dev/null || true
fi

# Step 7: Pull latest image
log "Pulling NetMirror image: $IMAGE"
if ! docker pull "$IMAGE"; then
    error "Failed to pull image. Please check your network connection."
fi

# Step 8: Start container
log "Starting container..."
docker run -d \
    --name "$CONTAINER_NAME" \
    --restart always \
    --network host \
    --env-file .env \
    -v "$(pwd)/data:/data" \
    "$IMAGE"

# Wait for container to be ready
log "Waiting for container to start..."
sleep 5

# Verify container is running
if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
    echo ""
    error "Container failed to start. Check logs with: docker logs $CONTAINER_NAME"
fi

# Step 9: Register with master node
log "Registering with master node..."
REGISTER_RESPONSE=$(curl -s -X POST "$MASTER_URL/api/register" \
    -H "Content-Type: application/json" \
    -d "{\"token\":\"$TOKEN\",\"url\":\"$NODE_URL\"}" \
    2>/dev/null)

if echo "$REGISTER_RESPONSE" | grep -q '"success":true'; then
    success "Node registered successfully with master!"
else
    warn "Registration response: $REGISTER_RESPONSE"
    warn "Node is running but registration may have failed."
    warn "You can manually add this node in the master's admin panel."
fi

# Done!
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║             Installation Complete!                           ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}Node Name:${NC}     $NODE_NAME"
echo -e "  ${CYAN}Location:${NC}      $NODE_LOCATION"
echo -e "  ${CYAN}Node URL:${NC}      $NODE_URL"
echo -e "  ${CYAN}Master URL:${NC}    $MASTER_URL"
echo -e "  ${CYAN}Container:${NC}     $CONTAINER_NAME"
echo ""
echo -e "${YELLOW}Useful Commands:${NC}"
echo -e "  View logs:     ${CYAN}docker logs -f $CONTAINER_NAME${NC}"
echo -e "  Restart:       ${CYAN}docker restart $CONTAINER_NAME${NC}"
echo -e "  Stop:          ${CYAN}docker stop $CONTAINER_NAME${NC}"
echo -e "  Remove:        ${CYAN}docker rm -f $CONTAINER_NAME${NC}"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo -e "  Edit config:   ${CYAN}nano $DEPLOY_DIR/.env${NC}"
echo -e "  After editing: ${CYAN}docker restart $CONTAINER_NAME${NC}"
echo ""
`

// generateInstallScript generates the install script for a token
func generateInstallScript(token *RegistrationToken, masterURL string) string {
	tmpl := template.Must(template.New("install").Parse(installScriptTemplate))
	var buf bytes.Buffer
	data := map[string]string{
		"MasterURL":    masterURL,
		"Token":        token.Token,
		"NodeName":     token.Name,
		"NodeLocation": token.Location,
		"ExpiresAt":    token.ExpiresAt.Format("2006-01-02 15:04:05 UTC"),
	}
	tmpl.Execute(&buf, data)
	return buf.String()
}
